LOAD DATA
INFILE './GeoLiteCity-Location.csv'
INTO TABLE ip2city_location
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(
 LOCID CHAR,
 COUNTRY CHAR,
 REGION CHAR,
 CITY CHAR,
 POSTALCODE CHAR,
 LATITUDE "TO_NUMBER(:\"LATITUDE\", '999999D999999', 'NLS_NUMERIC_CHARACTERS=''.,''')",
 LONGITUDE "TO_NUMBER(:\"LONGITUDE\", '999999D999999', 'NLS_NUMERIC_CHARACTERS=''.,''')",
 METROCODE INTEGER EXTERNAL,
 AREACODE INTEGER EXTERNAL
)
